auth-server: http://localhost:5555/auth
server:
    port: 4444
    context-path: /
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: web
      clientSecret: web_secret
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      scope: user_read, user_write
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
spring:
  thymeleaf:
    cache: false
    suffix: .html
    content-type: text/html
  jackson:
      date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

logging:
  level:
    org.springframework.security: DEBUG


