spring:
  application:
    name: auth-server
  datasource:
    url:  jdbc:mysql://localhost:3306/auth2017?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 654321
  jpa:
    hibernate:
      ddl-auto: none
#    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
debug: false
server:
  port: 5555
  context-path: /auth
security:
  oauth2:
    resource:
      filter-order: 3
